config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
  get 'order/home'
  get 'order/cart'
  root "home#index"
  get 'user_sign_up', to:"user#sign_up"
  post 'user_sign_up', to: "user#create"
  get 'user_login', to:"user#login"
  post 'user_login', to:"user#login"
  get "user_log_out", to:"user#logout"
  get "home", to: "home#index"
  get 'order/cart'
  get 'order/success'
  resources :items
  resources :products
  get 'home/index'
  get "admin_login", to:'admin#login'
  post "admin_login", to:'admin#login'
  get "admin_home", to:'admin#home'
  get "admin_order_history", to:"admin#order_history"
  get "admin_log_out", to:"admin#logout"
  get "user_addproduct", to:"user#add_product"
  get "cart_show", to:"cart#show"
  post "cart", to:"cart#save"
  get "checkout", to:"cart#checkout"
  post "checkout", to:"cart#checkout"
  get "purchase_complete", to:"cart#purchase_complete"
  get "user_order_history", to:"user#user_order_history"
  get "user_home" , to:"user#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/home.html.erb
<br>
<div class="mb-5">
<div class="d-inline p-2">Login as :- <%= @session %> </div>
<div class="d-inline p-2" style="margin-left:900px;">

<%= link_to "Logout", admin_log_out_path %>

</div>
</div>


<div class="container row m-auto g-auto align-items-center">
<div>
<%= link_to "Add Product", products_path,class:"btn btn-light" %>
</div>
<div>
<%= link_to "Add Item", items_path,class:"btn btn-light" %>
</div>
<div>
<%= link_to "Order History", admin_order_history_path,class:"btn btn-light" %>
</div>
</div>

app/views/admin/login.html.erb
<div class="container row m-auto g-auto align-items-center">
<div class="m-3">
<h1 class="mb-5">Admin Login</h1>
</div>





<%= form_with url:"admin_login", method: :post, local: true do |form| %>
  
  <div class="form-outline mb-4">
  <%= form.label :username ,"Username",class:"form-label"%> 
    <%= form.text_field :username, class: "form-control" %>
  
  </div>

 
  <div class="form-outline mb-4">
   
    <%= form.label :password,class: "form-label"  %> 
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
  

  
  
  <%= form.submit "Login", class: "btn btn-primary btn-block mb-4" %>


  </div>
  <% end %>
  </div>
  <%= link_to "Home", root_path %>

  

app/views/admin/order_history.html.erb
<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Oder_Id</th>
      <th>User Email</th>
      <th>Product</th>
      <th>Item</th>
      <th>Qauntity</th>
      

      
    </tr>
  </thead>
  <tbody>
    <% @order.each do |o| %>
      <tr>
        <td><%= o.id %></td>
        <td><%= o.user_email %></td> 
        <td><%= o.product.product_name %></td> 
        <td><%= o.item.item_name %></td> 
        <td><%= o.quantity %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<%= link_to "Home", admin_home_path %>
</div>