config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
  get 'order/home'
  get 'order/cart'
  root "home#index"
  get 'user_sign_up', to:"user#sign_up"
  post 'user_sign_up', to: "user#create"
  get 'user_login', to:"user#login"
  post 'user_login', to:"user#login"
  get "user_log_out", to:"user#logout"
  get "home", to: "home#index"
  get 'order/cart'
  get 'order/success'
  resources :items
  resources :products
  get 'home/index'
  get "admin_login", to:'admin#login'
  post "admin_login", to:'admin#login'
  get "admin_home", to:'admin#home'
  get "admin_order_history", to:"admin#order_history"
  get "admin_log_out", to:"admin#logout"
  get "user_addproduct", to:"user#add_product"
  get "cart_show", to:"cart#show"
  post "cart", to:"cart#save"
  get "checkout", to:"cart#checkout"
  post "checkout", to:"cart#checkout"
  get "purchase_complete", to:"cart#purchase_complete"
  get "user_order_history", to:"user#user_order_history"
  get "user_home" , to:"user#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders
    validates :name, presence: true
    validates :password, presence: true
    validates_format_of :email, :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
    
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :verify_authenticity_token
  # before_action :find_items
  
  def sign_up
    @user=User.new
  end


  def create
    @user=User.new(user_params)
    if @user.save
      flash[:notice]="Registration Successful!!!"
      redirect_to home_path
    else
      flash[:notice]="Please give valid input!!!"
      render :sign_up
    end
  end


  def login
    if request.post?
      search_user=User.find_by_email(user_params[:email])
      current_user=user_params.clone
      if search_user != nil
        if search_user[:password]==current_user[:password].to_i
          session[:user]=search_user[:email]
          redirect_to user_home_path
        else      
          flash[:notice]="Wrong Passowrd"
        end

      else
      flash[:notice]="User not registered"
      end
    end
  end
                   
  def home
    @session=session[:user] 
  end
  def add_product
    @item=Item.all
    @session=session[:user]
    
    if params[:product].present?
      @item = Product.find(params[:product]).items
      
    else
      @item = Item.all
      
    end
    if request.xhr?
      respond_to do |format|
          format.json {
              render json: {item: @item}
          }
      end
    end
  end


  def user_order_history
    email=params[:session]
  
    @orders = Order.where(user_email: email)
    p @orders
    p"--------------------------find---------------"

    
  end

  def logout
    session[:user]=nil
    flash[:notice]="You Logout successfully"
    redirect_to root_path
  end

  # def find_items
  #   @found_item=Item.find(params[:id])
  # end

  private
  def user_params
    params.permit(:name, :email, :password)
  end

  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/add_product.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <script src="/jquery/jquery.js"></script>-->
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script>
$("#item_id").prop("disabled", true); // second dropdown is disable while first dropdown is empty
console.log("atleast loaded")
$(document).ready(function(){


  $("#product_id").change(function(){
    
    console.log("change function called")
  	var product = $(this).val();
  	if(product == ''){
  		$("#item_id").prop("disabled", true);
  	}else{
  		$("#item_id").prop("disabled", false);
  	}
  	$.ajax({
	    url: "user_addproduct",
	    method: "GET",  
	    dataType: "json",
	    data: {product: product},
	    error: function (xhr, status, error) {
            console.log("error called")
	      	console.error('AJAX Error: ' + status + error);
	    },
	    success: function (response) {
	      	console.log(response);
            console.log("success function called")
	      	var item = response["item"];
	      	$("#item_id").empty();
            console.log("function called after item_id", item)
	      	$("#item_id").append('<option>Select Item</option>');
	      	for(var i = 0; i < item.length; i++){
                console.log(i, " ", item[i]["id"]);
	      		$("#item_id").append('<option value="' + item[i]["id"] + '">' +item[i]["item_name"] + '</option>');
	      	}
	    }
  	});


  });
});
 
</script>


<div class="mb-5">
<div class="d-inline p-2" style="margin-left:900px;">

<%= link_to "Logout", user_log_out_path %>

</div>
<div class="d-inline p-2"><h2>Order Page</h2></div>
</div>

<%= form_with xml: @item, url: cart_path, local: true do |form| %>
   <%= form.hidden_field :user_email,value: @session %>
  
    <div class="field form-outline mb-4">
    <%= form.label :product_id %>
    <%= form.select(:product_id, Product.all.collect {|p| [p.product_name, p.id]},  {class: 'form-control'}) %>
    </div>
    <div class="field form-outline mb-4">
    <%= form.label :item_id %>
    <%= form.select(:item_id, Item.all.collect {|p| [p.item_name, p.id]},  {class: 'form-control'}) %> 
    </div>
    <div class="field form-outline mb-4">
    <%= form.label :quantity %> 
    <%= form.number_field :quantity,  min: 1 %>
   
    </div>
    <div class="actions">
    <%= form.submit "BUY" ,class: "btn btn-primary btn-block mb-4" %>
  </div>
<% end %>

<div>
<%= link_to "Home", user_home_path %>
</div>



</body>
</html>

app/views/user/home.html.erb
<div class="container row m-auto g-auto align-items-center">
<div class="mb-5">
<div class="d-inline p-2" style="margin-left:900px;">

<%= link_to "Logout", user_log_out_path %>

</div>
<div>
<%= link_to "Add Product", user_addproduct_path,class:"btn btn-light" %>
</div>

<div>
<%= link_to "Order History", user_order_history_path(:session=>@session),class:"btn btn-light" %>
</div>
</div>

app/views/user/login.html.erb
<div class="mb-3">
<h1>User Login</h1>
</div>



<%= form_with url:"user_login", method: :post, local: true do |form| %>
   
    <div class="form-outline mb-4">
    <%= form.label :email ,"Email",class:"form-label"%> 
    <%= form.text_field :email, class: "form-control" %>
    </div>
  
   
    <div class="form-outline mb-4">
     
      <%= form.label :password,class: "form-label"  %> 
      <%= form.password_field :password, class: "form-control" %>
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
    
  
    
    
    <%= form.submit "Login", class: "btn btn-primary btn-block mb-4" %>
  
  
    </div>
    <% end %>
    </div>

<%= link_to "Home", root_path %>

app/views/user/order_history.html.erb
<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Oder_Id</th>
      <th>Product</th>
      <th>Item</th>
      <th>Quantity</th>
      
    </tr>
  </thead>
  <tbody>
    <% @order.each do |o| %>
      <tr>
        <td><%= o.id %></td>
        <td><%= o.product.product_name %></td> 
        <td><%= o.item.item_name %></td> 
        <td><%= o.quantity %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<%= link_to "Home", admin_home_path %>
</div>

app/views/user/sign_up.html.erb
<div class="mb-3">
<h1>User Sign UP</h1>
</div>


<%= form_with url:"user_sign_up", method: :post, local: true do |form| %>
  
    <div class="form-outline mb-4">
    <%= form.label :name ,"Name",class:"form-label"%> 
    <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-outline mb-4">
    <%= form.label :email ,"Email",class:"form-label"%> 
    <%= form.text_field :email, class: "form-control" %>
    </div>
  
   
    <div class="form-outline mb-4">
     
      <%= form.label :password,class: "form-label"  %> 
      <%= form.password_field :password, class: "form-control" %>
    </div>
  
    <!-- 2 column grid layout for inline styling -->
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
    
  
    
    
    <%= form.submit "Sign UP", class: "btn btn-primary btn-block mb-4" %>
  
  
    </div>
    <% end %>
    </div>

<%= link_to "Home", root_path %>

app/views/user/user_order_history.html.erb
<h1> Your Orders </h1>
<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Oder_Id</th>
      <th>Product</th>
      <th>Item</th>
      <th>Qauntity</th>
      

      
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |o| %>
      <tr>
        <td><%= o.id %></td>
        
        <td><%= o.product.product_name %></td> 
        <td><%= o.item.item_name %></td> 
        <td><%= o.quantity %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<%= link_to "Home", user_home_path %>
</div>