config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
  get 'order/home'
  get 'order/cart'
  root "home#index"
  get 'user_sign_up', to:"user#sign_up"
  post 'user_sign_up', to: "user#create"
  get 'user_login', to:"user#login"
  post 'user_login', to:"user#login"
  get "user_log_out", to:"user#logout"
  get "home", to: "home#index"
  get 'order/cart'
  get 'order/success'
  resources :items
  resources :products
  get 'home/index'
  get "admin_login", to:'admin#login'
  post "admin_login", to:'admin#login'
  get "admin_home", to:'admin#home'
  get "admin_order_history", to:"admin#order_history"
  get "admin_log_out", to:"admin#logout"
  get "user_addproduct", to:"user#add_product"
  get "cart_show", to:"cart#show"
  post "cart", to:"cart#save"
  get "checkout", to:"cart#checkout"
  post "checkout", to:"cart#checkout"
  get "purchase_complete", to:"cart#purchase_complete"
  get "user_order_history", to:"user#user_order_history"
  get "user_home" , to:"user#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
    has_many :items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :admin_loggedin?
  
  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:product_name)
    end
    
    def admin_loggedin?
      if session[:admin].nil?
        flash[:notice]="Login as an Admin to continue from product"
        redirect_to admin_login_path
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>



<br>


<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              
              <th colspan="3">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= product.product_name %></td>
               
                <td><button type="button" class="btn btn-info"><%= link_to 'Show', product %></button></td>
                <td><button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_product_path(product) %></button></td>
                <td><button type="button" class="btn btn-danger"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to 'New Product', new_product_path %>
      <%= link_to 'Home', admin_home_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>